name: CI

on: [push]

jobs:
  test:
    name: test ${{ matrix.node }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [10.x]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install yarn

    - run: yarn

    - run: yarn lint

    - run: yarn build

    - run: yarn test

    - name: Dispatch Success
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: tests
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
