name: Publish

on: [push]

# on:
#   pull_request:
#     branches:
#       - master
#     types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
        registry-url: 'https://npm.pkg.github.com'

    - run: yarn install

    - run: yarn build

    - name: Publish
    - run: yarn publish:async
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
