name: Publish

# on:
#   push:
#     paths:
#       - 'packages/async/**'

# on: [push]

on: 
  repository_dispatch:
    types: [tests-passed]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - run: npm install yarn

      - run: yarn

      - run: yarn build

      - run: yarn lint